set(_CATKIN_CURRENT_PACKAGE "agvs_robot_control")
set(agvs_robot_control_VERSION "0.1.3")
set(agvs_robot_control_MAINTAINER "Roberto Guzmán <rguzman@robotnik.es>, Román Navarro <rnavarro@robotnik.es>")
set(agvs_robot_control_PACKAGE_FORMAT "1")
set(agvs_robot_control_BUILD_DEPENDS "robotnik_msgs" "roscpp" "sensor_msgs" "std_srvs" "std_msgs" "tf" "message_generation" "ackermann_msgs" "nav_msgs" "geometry_msgs" "diagnostic_msgs" "diagnostic_updater")
set(agvs_robot_control_BUILD_EXPORT_DEPENDS "robotnik_msgs" "roscpp" "sensor_msgs" "std_srvs" "std_msgs" "tf" "message_runtime" "ackermann_msgs" "nav_msgs" "geometry_msgs" "diagnostic_msgs" "diagnostic_updater")
set(agvs_robot_control_BUILDTOOL_DEPENDS "catkin")
set(agvs_robot_control_BUILDTOOL_EXPORT_DEPENDS )
set(agvs_robot_control_EXEC_DEPENDS "robotnik_msgs" "roscpp" "sensor_msgs" "std_srvs" "std_msgs" "tf" "message_runtime" "ackermann_msgs" "nav_msgs" "geometry_msgs" "diagnostic_msgs" "diagnostic_updater")
set(agvs_robot_control_RUN_DEPENDS "robotnik_msgs" "roscpp" "sensor_msgs" "std_srvs" "std_msgs" "tf" "message_runtime" "ackermann_msgs" "nav_msgs" "geometry_msgs" "diagnostic_msgs" "diagnostic_updater")
set(agvs_robot_control_TEST_DEPENDS )
set(agvs_robot_control_DOC_DEPENDS )
set(agvs_robot_control_URL_WEBSITE "http://wiki.ros.org/agvs_robot_control")
set(agvs_robot_control_URL_BUGTRACKER "https://github.com/RobotnikAutomation/agvs_sim/issues")
set(agvs_robot_control_URL_REPOSITORY "https://github.com/RobotnikAutomation/agvs_sim")
set(agvs_robot_control_DEPRECATED "")