set(_CATKIN_CURRENT_PACKAGE "agvs_gazebo")
set(agvs_gazebo_VERSION "0.1.3")
set(agvs_gazebo_MAINTAINER "Roberto Guzmán <rguzman@robotnik.es>, Román Navarro <rnavarro@robotnik.es>")
set(agvs_gazebo_PACKAGE_FORMAT "1")
set(agvs_gazebo_BUILD_DEPENDS "agvs_description" "agvs_pad" "agvs_robot_control" "gazebo_ros" "roscpp" "std_msgs" "std_srvs" "tf" "joint_state_controller" "velocity_controllers" "effort_controllers")
set(agvs_gazebo_BUILD_EXPORT_DEPENDS "agvs_description" "agvs_pad" "agvs_robot_control" "gazebo_ros" "roscpp" "std_msgs" "std_srvs" "tf" "joint_state_controller" "velocity_controllers" "effort_controllers")
set(agvs_gazebo_BUILDTOOL_DEPENDS "catkin")
set(agvs_gazebo_BUILDTOOL_EXPORT_DEPENDS )
set(agvs_gazebo_EXEC_DEPENDS "agvs_description" "agvs_pad" "agvs_robot_control" "gazebo_ros" "roscpp" "std_msgs" "std_srvs" "tf" "joint_state_controller" "velocity_controllers" "effort_controllers")
set(agvs_gazebo_RUN_DEPENDS "agvs_description" "agvs_pad" "agvs_robot_control" "gazebo_ros" "roscpp" "std_msgs" "std_srvs" "tf" "joint_state_controller" "velocity_controllers" "effort_controllers")
set(agvs_gazebo_TEST_DEPENDS )
set(agvs_gazebo_DOC_DEPENDS )
set(agvs_gazebo_URL_WEBSITE "http://wiki.ros.org/agvs_gazebo")
set(agvs_gazebo_URL_BUGTRACKER "https://github.com/RobotnikAutomation/agvs_sim/issues")
set(agvs_gazebo_URL_REPOSITORY "https://github.com/RobotnikAutomation/agvs_sim")
set(agvs_gazebo_DEPRECATED "")