set(_CATKIN_CURRENT_PACKAGE "agvs_pad")
set(agvs_pad_VERSION "0.1.3")
set(agvs_pad_MAINTAINER "Román Navarro <rnavarro@robotnik.es>")
set(agvs_pad_PACKAGE_FORMAT "1")
set(agvs_pad_BUILD_DEPENDS "geometry_msgs" "std_msgs" "sensor_msgs" "diagnostic_msgs" "diagnostic_updater" "robotnik_msgs" "ackermann_msgs" "std_srvs")
set(agvs_pad_BUILD_EXPORT_DEPENDS "geometry_msgs" "std_msgs" "sensor_msgs" "diagnostic_msgs" "diagnostic_updater" "robotnik_msgs" "ackermann_msgs" "std_srvs")
set(agvs_pad_BUILDTOOL_DEPENDS "catkin")
set(agvs_pad_BUILDTOOL_EXPORT_DEPENDS )
set(agvs_pad_EXEC_DEPENDS "geometry_msgs" "std_msgs" "sensor_msgs" "diagnostic_msgs" "diagnostic_updater" "robotnik_msgs" "ackermann_msgs" "std_srvs")
set(agvs_pad_RUN_DEPENDS "geometry_msgs" "std_msgs" "sensor_msgs" "diagnostic_msgs" "diagnostic_updater" "robotnik_msgs" "ackermann_msgs" "std_srvs")
set(agvs_pad_TEST_DEPENDS )
set(agvs_pad_DOC_DEPENDS )
set(agvs_pad_URL_WEBSITE "http://wiki.ros.org/agvs_pad")
set(agvs_pad_URL_BUGTRACKER "https://github.com/RobotnikAutomation/agvs_common/issues")
set(agvs_pad_URL_REPOSITORY "https://github.com/RobotnikAutomation/agvs_common.git")
set(agvs_pad_DEPRECATED "")