set(_CATKIN_CURRENT_PACKAGE "agvs_control")
set(agvs_control_VERSION "0.1.3")
set(agvs_control_MAINTAINER "Román Navarro <rnavarro@robotnik.es>, Roberto Guzmán <rguzman@robotnik.es>")
set(agvs_control_PACKAGE_FORMAT "1")
set(agvs_control_BUILD_DEPENDS )
set(agvs_control_BUILD_EXPORT_DEPENDS )
set(agvs_control_BUILDTOOL_DEPENDS "catkin")
set(agvs_control_BUILDTOOL_EXPORT_DEPENDS )
set(agvs_control_EXEC_DEPENDS )
set(agvs_control_RUN_DEPENDS )
set(agvs_control_TEST_DEPENDS )
set(agvs_control_DOC_DEPENDS )
set(agvs_control_URL_WEBSITE "http://wiki.ros.org/agvs_control")
set(agvs_control_URL_BUGTRACKER "https://github.com/RobotnikAutomation/agvs_sim/issues")
set(agvs_control_URL_REPOSITORY "https://github.com/RobotnikAutomation/agvs_sim")
set(agvs_control_DEPRECATED "")