set(_CATKIN_CURRENT_PACKAGE "agvs_sim_bringup")
set(agvs_sim_bringup_VERSION "0.1.3")
set(agvs_sim_bringup_MAINTAINER "Roberto Guzmán <rguzman@robotnik.es>, Román Navarro <rnavarro@robotnik.es>")
set(agvs_sim_bringup_PACKAGE_FORMAT "1")
set(agvs_sim_bringup_BUILD_DEPENDS )
set(agvs_sim_bringup_BUILD_EXPORT_DEPENDS )
set(agvs_sim_bringup_BUILDTOOL_DEPENDS "catkin")
set(agvs_sim_bringup_BUILDTOOL_EXPORT_DEPENDS )
set(agvs_sim_bringup_EXEC_DEPENDS )
set(agvs_sim_bringup_RUN_DEPENDS )
set(agvs_sim_bringup_TEST_DEPENDS )
set(agvs_sim_bringup_DOC_DEPENDS )
set(agvs_sim_bringup_URL_WEBSITE "http://wiki.ros.org/agvs_sim_bringup")
set(agvs_sim_bringup_URL_BUGTRACKER "https://github.com/RobotnikAutomation/agvs_sim/issues")
set(agvs_sim_bringup_URL_REPOSITORY "https://github.com/RobotnikAutomation/agvs_sim")
set(agvs_sim_bringup_DEPRECATED "")