set(_CATKIN_CURRENT_PACKAGE "agvs_common")
set(agvs_common_VERSION "0.1.3")
set(agvs_common_MAINTAINER "Roberto Guzmán <rguzman@robotnik.es>, Román Navarro <rnavarro@robotnik.es>")
set(agvs_common_PACKAGE_FORMAT "1")
set(agvs_common_BUILD_DEPENDS )
set(agvs_common_BUILD_EXPORT_DEPENDS "agvs_description" "agvs_pad")
set(agvs_common_BUILDTOOL_DEPENDS "catkin")
set(agvs_common_BUILDTOOL_EXPORT_DEPENDS )
set(agvs_common_EXEC_DEPENDS "agvs_description" "agvs_pad")
set(agvs_common_RUN_DEPENDS "agvs_description" "agvs_pad")
set(agvs_common_TEST_DEPENDS )
set(agvs_common_DOC_DEPENDS )
set(agvs_common_URL_WEBSITE "http://wiki.ros.org/agvs_common")
set(agvs_common_URL_BUGTRACKER "https://github.com/RobotnikAutomation/agvs_common/issues")
set(agvs_common_URL_REPOSITORY "")
set(agvs_common_DEPRECATED "")