set(_CATKIN_CURRENT_PACKAGE "agvs_sim")
set(agvs_sim_VERSION "0.1.3")
set(agvs_sim_MAINTAINER "Roberto Guzmán <rguzman@robotnik.es>, Román Navarro <rnavarro@robotnik.es>")
set(agvs_sim_PACKAGE_FORMAT "1")
set(agvs_sim_BUILD_DEPENDS )
set(agvs_sim_BUILD_EXPORT_DEPENDS "agvs_gazebo" "agvs_robot_control" "agvs_control" "agvs_sim_bringup")
set(agvs_sim_BUILDTOOL_DEPENDS "catkin")
set(agvs_sim_BUILDTOOL_EXPORT_DEPENDS )
set(agvs_sim_EXEC_DEPENDS "agvs_gazebo" "agvs_robot_control" "agvs_control" "agvs_sim_bringup")
set(agvs_sim_RUN_DEPENDS "agvs_gazebo" "agvs_robot_control" "agvs_control" "agvs_sim_bringup")
set(agvs_sim_TEST_DEPENDS )
set(agvs_sim_DOC_DEPENDS )
set(agvs_sim_URL_WEBSITE "http://ros.org/wiki/agvs_sim")
set(agvs_sim_URL_BUGTRACKER "https://github.com/RobotnikAutomation/agvs_sim/issues")
set(agvs_sim_URL_REPOSITORY "")
set(agvs_sim_DEPRECATED "")