# generated from genmsg/cmake/pkg-genmsg.context.in

messages_str = "/home/shydh/catkin_ws/src/robotnik_msgs/msg/encoders.msg;/home/shydh/catkin_ws/src/robotnik_msgs/msg/inputs_outputs.msg;/home/shydh/catkin_ws/src/robotnik_msgs/msg/ptz.msg;/home/shydh/catkin_ws/src/robotnik_msgs/msg/Data.msg;/home/shydh/catkin_ws/src/robotnik_msgs/msg/Interfaces.msg;/home/shydh/catkin_ws/src/robotnik_msgs/msg/Axis.msg;/home/shydh/catkin_ws/src/robotnik_msgs/msg/AlarmSensor.msg;/home/shydh/catkin_ws/src/robotnik_msgs/msg/Alarms.msg;/home/shydh/catkin_ws/src/robotnik_msgs/msg/MotorStatus.msg;/home/shydh/catkin_ws/src/robotnik_msgs/msg/MotorsStatus.msg;/home/shydh/catkin_ws/src/robotnik_msgs/msg/State.msg;/home/shydh/catkin_ws/src/robotnik_msgs/msg/BatteryStatus.msg;/home/shydh/catkin_ws/src/robotnik_msgs/msg/BatteryStatusStamped.msg;/home/shydh/catkin_ws/src/robotnik_msgs/msg/MotorsStatusDifferential.msg;/home/shydh/catkin_ws/src/robotnik_msgs/msg/InverterStatus.msg;/home/shydh/catkin_ws/src/robotnik_msgs/msg/RobotnikMotorsStatus.msg;/home/shydh/catkin_ws/src/robotnik_msgs/msg/ElevatorAction.msg;/home/shydh/catkin_ws/src/robotnik_msgs/msg/ElevatorStatus.msg;/home/shydh/catkin_ws/src/robotnik_msgs/msg/Cartesian_Euler_pose.msg;/home/shydh/catkin_ws/src/robotnik_msgs/msg/alarmmonitor.msg;/home/shydh/catkin_ws/src/robotnik_msgs/msg/alarmsmonitor.msg;/home/shydh/catkin_ws/src/robotnik_msgs/msg/named_inputs_outputs.msg;/home/shydh/catkin_ws/src/robotnik_msgs/msg/named_input_output.msg;/home/shydh/catkin_ws/src/robotnik_msgs/msg/StringArray.msg;/home/shydh/catkin_ws/src/robotnik_msgs/msg/LaserMode.msg;/home/shydh/catkin_ws/src/robotnik_msgs/msg/LaserStatus.msg;/home/shydh/catkin_ws/src/robotnik_msgs/msg/SafetyModuleStatus.msg;/home/shydh/catkin_ws/src/robotnik_msgs/msg/SubState.msg;/home/shydh/catkin_ws/src/robotnik_msgs/msg/BatteryDockingStatus.msg;/home/shydh/catkin_ws/src/robotnik_msgs/msg/BatteryDockingStatusStamped.msg;/home/shydh/catkin_ws/src/robotnik_msgs/msg/BoolArray.msg;/home/shydh/catkin_ws/devel/share/robotnik_msgs/msg/SetElevatorAction.msg;/home/shydh/catkin_ws/devel/share/robotnik_msgs/msg/SetElevatorActionGoal.msg;/home/shydh/catkin_ws/devel/share/robotnik_msgs/msg/SetElevatorActionResult.msg;/home/shydh/catkin_ws/devel/share/robotnik_msgs/msg/SetElevatorActionFeedback.msg;/home/shydh/catkin_ws/devel/share/robotnik_msgs/msg/SetElevatorGoal.msg;/home/shydh/catkin_ws/devel/share/robotnik_msgs/msg/SetElevatorResult.msg;/home/shydh/catkin_ws/devel/share/robotnik_msgs/msg/SetElevatorFeedback.msg"
services_str = "/home/shydh/catkin_ws/src/robotnik_msgs/srv/get_digital_input.srv;/home/shydh/catkin_ws/src/robotnik_msgs/srv/set_analog_output.srv;/home/shydh/catkin_ws/src/robotnik_msgs/srv/set_mode.srv;/home/shydh/catkin_ws/src/robotnik_msgs/srv/set_ptz.srv;/home/shydh/catkin_ws/src/robotnik_msgs/srv/get_mode.srv;/home/shydh/catkin_ws/src/robotnik_msgs/srv/set_digital_output.srv;/home/shydh/catkin_ws/src/robotnik_msgs/srv/set_odometry.srv;/home/shydh/catkin_ws/src/robotnik_msgs/srv/set_height.srv;/home/shydh/catkin_ws/src/robotnik_msgs/srv/enable_disable.srv;/home/shydh/catkin_ws/src/robotnik_msgs/srv/home.srv;/home/shydh/catkin_ws/src/robotnik_msgs/srv/axis_record.srv;/home/shydh/catkin_ws/src/robotnik_msgs/srv/set_float_value.srv;/home/shydh/catkin_ws/src/robotnik_msgs/srv/SetMotorStatus.srv;/home/shydh/catkin_ws/src/robotnik_msgs/srv/SetElevator.srv;/home/shydh/catkin_ws/src/robotnik_msgs/srv/get_alarms.srv;/home/shydh/catkin_ws/src/robotnik_msgs/srv/ack_alarm.srv;/home/shydh/catkin_ws/src/robotnik_msgs/srv/set_modbus_register.srv;/home/shydh/catkin_ws/src/robotnik_msgs/srv/get_modbus_register.srv;/home/shydh/catkin_ws/src/robotnik_msgs/srv/GetBool.srv;/home/shydh/catkin_ws/src/robotnik_msgs/srv/set_CartesianEuler_pose.srv;/home/shydh/catkin_ws/src/robotnik_msgs/srv/set_named_digital_output.srv;/home/shydh/catkin_ws/src/robotnik_msgs/srv/SetLaserMode.srv;/home/shydh/catkin_ws/src/robotnik_msgs/srv/ResetFromSubState.srv"
pkg_name = "robotnik_msgs"
dependencies_str = "actionlib_msgs;std_msgs"
langs = "gencpp;geneus;genlisp;gennodejs;genpy"
dep_include_paths_str = "robotnik_msgs;/home/shydh/catkin_ws/src/robotnik_msgs/msg;robotnik_msgs;/home/shydh/catkin_ws/devel/share/robotnik_msgs/msg;actionlib_msgs;/opt/ros/melodic/share/actionlib_msgs/cmake/../msg;std_msgs;/opt/ros/melodic/share/std_msgs/cmake/../msg"
PYTHON_EXECUTABLE = "/usr/bin/python2"
package_has_static_sources = '' == 'TRUE'
genmsg_check_deps_script = "/opt/ros/melodic/share/genmsg/cmake/../../../lib/genmsg/genmsg_check_deps.py"
