set(_CATKIN_CURRENT_PACKAGE "agvs_description")
set(agvs_description_VERSION "0.1.3")
set(agvs_description_MAINTAINER "Roberto Guzmán <rguzman@robotnik.es>, Román Navarro <rnavarro@robotnik.es>")
set(agvs_description_PACKAGE_FORMAT "1")
set(agvs_description_BUILD_DEPENDS "roscpp" "std_msgs" "std_srvs" "tf")
set(agvs_description_BUILD_EXPORT_DEPENDS "message_runtime" "roscpp" "std_msgs" "std_srvs" "tf")
set(agvs_description_BUILDTOOL_DEPENDS "catkin")
set(agvs_description_BUILDTOOL_EXPORT_DEPENDS )
set(agvs_description_EXEC_DEPENDS "message_runtime" "roscpp" "std_msgs" "std_srvs" "tf")
set(agvs_description_RUN_DEPENDS "message_runtime" "roscpp" "std_msgs" "std_srvs" "tf")
set(agvs_description_TEST_DEPENDS )
set(agvs_description_DOC_DEPENDS )
set(agvs_description_URL_WEBSITE "http://wiki.ros.org/agvs_description")
set(agvs_description_URL_BUGTRACKER "https://github.com/RobotnikAutomation/agvs_common/issues")
set(agvs_description_URL_REPOSITORY "https://github.com/RobotnikAutomation/agvs_common.git")
set(agvs_description_DEPRECATED "")