set(_CATKIN_CURRENT_PACKAGE "rbx2_msgs")
set(rbx2_msgs_VERSION "0.1.0")
set(rbx2_msgs_MAINTAINER "Patrick Goebel <patrick@pirobot.org>")
set(rbx2_msgs_PACKAGE_FORMAT "1")
set(rbx2_msgs_BUILD_DEPENDS "roscpp" "rospy" "message_generation")
set(rbx2_msgs_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "message_runtime")
set(rbx2_msgs_BUILDTOOL_DEPENDS "catkin")
set(rbx2_msgs_BUILDTOOL_EXPORT_DEPENDS )
set(rbx2_msgs_EXEC_DEPENDS "roscpp" "rospy" "message_runtime")
set(rbx2_msgs_RUN_DEPENDS "roscpp" "rospy" "message_runtime")
set(rbx2_msgs_TEST_DEPENDS )
set(rbx2_msgs_DOC_DEPENDS )
set(rbx2_msgs_URL_WEBSITE "http://ros.org/wiki/rbx2_msgs")
set(rbx2_msgs_URL_BUGTRACKER "https://github.com/pirobot/rbx2/issues")
set(rbx2_msgs_URL_REPOSITORY "")
set(rbx2_msgs_DEPRECATED "")