set(_CATKIN_CURRENT_PACKAGE "rbx2_utils")
set(rbx2_utils_VERSION "0.1.0")
set(rbx2_utils_MAINTAINER "Patrick Goebel <patrick@pirobot.org>")
set(rbx2_utils_PACKAGE_FORMAT "1")
set(rbx2_utils_BUILD_DEPENDS "roscpp" "rospy" "std_msgs" "diagnostic_msgs" "dynamic_reconfigure" "rbx2_msgs" "dynamixel_controllers" "dynamixel_msgs" "message_generation")
set(rbx2_utils_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs" "diagnostic_msgs" "dynamic_reconfigure" "rbx2_msgs" "dynamixel_controllers" "dynamixel_msgs" "message_runtime")
set(rbx2_utils_BUILDTOOL_DEPENDS "catkin")
set(rbx2_utils_BUILDTOOL_EXPORT_DEPENDS )
set(rbx2_utils_EXEC_DEPENDS "roscpp" "rospy" "std_msgs" "diagnostic_msgs" "dynamic_reconfigure" "rbx2_msgs" "dynamixel_controllers" "dynamixel_msgs" "message_runtime")
set(rbx2_utils_RUN_DEPENDS "roscpp" "rospy" "std_msgs" "diagnostic_msgs" "dynamic_reconfigure" "rbx2_msgs" "dynamixel_controllers" "dynamixel_msgs" "message_runtime")
set(rbx2_utils_TEST_DEPENDS )
set(rbx2_utils_DOC_DEPENDS )
set(rbx2_utils_URL_WEBSITE "http://ros.org/wiki/rbx2_apps")
set(rbx2_utils_URL_BUGTRACKER "https://github.com/pirobot/rbx2/utils")
set(rbx2_utils_URL_REPOSITORY "")
set(rbx2_utils_DEPRECATED "")