set(_CATKIN_CURRENT_PACKAGE "rep_ryw")
set(rep_ryw_VERSION "0.0.0")
set(rep_ryw_MAINTAINER "shydh <shydh@todo.todo>")
set(rep_ryw_PACKAGE_FORMAT "2")
set(rep_ryw_BUILD_DEPENDS "roscpp" "rospy" "std_msgs" "geometry_msgs" "tf" "gazebo_ros" "controller_manager" "joint_state_controller" "robot_state_publisher" "pluginlib" "controller_manager_msgs")
set(rep_ryw_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs" "geometry_msgs" "tf" "gazebo_ros" "controller_manager" "joint_state_controller" "robot_state_publisher" "pluginlib" "controller_manager_msgs")
set(rep_ryw_BUILDTOOL_DEPENDS "catkin")
set(rep_ryw_BUILDTOOL_EXPORT_DEPENDS )
set(rep_ryw_EXEC_DEPENDS "roscpp" "rospy" "std_msgs" "geometry_msgs" "tf" "gazebo_ros" "controller_manager" "joint_state_controller" "robot_state_publisher" "pluginlib" "controller_manager_msgs")
set(rep_ryw_RUN_DEPENDS "roscpp" "rospy" "std_msgs" "geometry_msgs" "tf" "gazebo_ros" "controller_manager" "joint_state_controller" "robot_state_publisher" "pluginlib" "controller_manager_msgs")
set(rep_ryw_TEST_DEPENDS )
set(rep_ryw_DOC_DEPENDS )
set(rep_ryw_URL_WEBSITE "")
set(rep_ryw_URL_BUGTRACKER "")
set(rep_ryw_URL_REPOSITORY "")
set(rep_ryw_DEPRECATED "")