# CMake generated Testfile for 
# Source directory: /home/shydh/catkin_ws/src
# Build directory: /home/shydh/catkin_ws/src
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
subdirs("gtest")
subdirs("agvs_common/agvs_common")
subdirs("agvs_simk/agvs_control")
subdirs("agvs_simk/agvs_sim")
subdirs("agvs_simk/agvs_sim_bringup")
subdirs("rbx1/rbx1")
subdirs("rbx2/rbx2")
subdirs("robotnik_msgs")
subdirs("rbx1/rbx1_speech")
subdirs("rbx2/rbx2_ar_tags")
subdirs("rbx2/rbx2_bringup")
subdirs("rbx2/rbx2_diagnostics")
subdirs("rbx2/rbx2_gazebo")
subdirs("rbx2/rbx2_gui")
subdirs("rbx2/rbx2_msgs")
subdirs("rbx2/rbx2_tasks")
subdirs("rbx2/rbx2_utils")
subdirs("agvs_common/agvs_pad")
subdirs("rbx1/rbx1_bringup")
subdirs("rbx1/rbx1_dynamixels")
subdirs("rbx1/rbx1_vision")
subdirs("rbx2/rbx2_dynamixels")
subdirs("rbx2/rbx2_vision")
subdirs("agvs_common/agvs_description")
subdirs("agvs_simk/agvs_robot_control")
subdirs("rbx1/rbx1_apps")
subdirs("rbx1/rbx1_nav")
subdirs("rbx2/rbx2_arm_nav")
subdirs("rbx2/rbx2_nav")
subdirs("rbx1/rbx1_description")
subdirs("rep_ryw")
subdirs("agvs_simk/agvs_gazebo")
subdirs("rbx2/rbx2_description")
subdirs("rbx2/grasping_pi_robot_moveit_config")
subdirs("rbx2/pedestal_pi_no_gripper_moveit_config")
subdirs("rbx2/pedestal_pi_with_gripper_moveit_config")
subdirs("rbx2/pi_robot_moveit_config")
