subscribers:
  - name:        "Safe reactive controller"
    topic:       "safety_controller"
    timeout:     1.0
    priority:    2
    
  - name:        "Joystick control"
    topic:       "/joystick_cmd_vel"
    timeout:     1.0
    priority:    1
    
  - name:        "Any node that publishes directly to /cmd_vel"
    topic:       "/cmd_vel"
    timeout:     1.0
    priority:    0
    
publisher:       "output/cmd_vel"
